In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [71]:
class PosyNet(nn.Module):

    def __init__(self):
        super(PosyNet, self).__init__()
        
        # input: 3-vector (x, y, z)
        # output: 1-vector (=xyz)
        
        self.powers = nn.Parameter(torch.rand(3,1))
        #self.powers = torch.FloatTensor([[0, -1, 1, 1, 1],[1, -2, 0, 2, 1], [0, -1, 0, 2, 1]]).t()
        
    def forward(self, x):
        
        p = self.powers
        
        #for j in range(3):
            #for i in range(5):
                #posy[j] = posy[j]*x[i]**self.powers[i,j]
        posy = x[0]**p[0,0] * x[1]**p[1,0] * x[2]**p[2,0]
        
        return posy
    
net = PosyNet()
print(net)

PosyNet()


In [72]:
list(net.parameters())

[Parameter containing:
 tensor([[0.7770],
         [0.8356],
         [0.5147]], requires_grad=True)]

In [73]:
x = torch.rand(3, requires_grad=True)
x

tensor([0.0758, 0.2644, 0.3309], requires_grad=True)

In [74]:
net(x)

tensor(0.0251, grad_fn=<MulBackward0>)

In [75]:
import torch.optim as optim

criterion = nn.MSELoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

In [76]:
def compute_actual(x):
    
    return x[0]**4*x[1]*x[2]
    

In [77]:
torch.log(net(x))

tensor(-3.6854, grad_fn=<LogBackward>)

In [78]:
running_loss = 0
for epoch in range(1000):
    state = torch.rand(3, requires_grad=True)
    actual = compute_actual(state).detach()
    
    optimizer.zero_grad()
    net_prediction = net(state)
    
    loss = criterion(torch.log(net_prediction), torch.log(actual))
    
    loss.backward()
    optimizer.step()
    
    running_loss += loss.item()
    
    if epoch%100==0: 
        
        print(running_loss/100)
        print(list(net.parameters()))
        running_loss = 0
    

0.12979503631591796
[Parameter containing:
tensor([[0.7835],
        [0.8401],
        [0.5235]], requires_grad=True)]
3.789665012208279
[Parameter containing:
tensor([[3.9746],
        [1.0466],
        [0.8397]], requires_grad=True)]
0.020536971029669927
[Parameter containing:
tensor([[4.0039],
        [0.9892],
        [1.0046]], requires_grad=True)]
3.0428085386802196e-05
[Parameter containing:
tensor([[4.0005],
        [0.9990],
        [1.0008]], requires_grad=True)]
3.4458209544396825e-07
[Parameter containing:
tensor([[4.0000],
        [0.9999],
        [1.0000]], requires_grad=True)]
6.346801573187122e-10
[Parameter containing:
tensor([[4.0000],
        [1.0000],
        [1.0000]], requires_grad=True)]
7.437037652380241e-12
[Parameter containing:
tensor([[4.0000],
        [1.0000],
        [1.0000]], requires_grad=True)]
3.221067856884474e-12
[Parameter containing:
tensor([[4.0000],
        [1.0000],
        [1.0000]], requires_grad=True)]
3.176703344820453e-12
[Parameter cont

In [59]:
list(net.parameters())

[Parameter containing:
 tensor([[4.0000],
         [1.0000],
         [1.0000]], requires_grad=True)]

In [87]:
x

tensor(0.3830, grad_fn=<SelectBackward>)

In [88]:
tgo = -3*z/vz
tgo

tensor(-3.2347, grad_fn=<DivBackward0>)

In [89]:
ax = -6*vx/tgo - 12*x/tgo**2
ax

tensor(-0.0818, grad_fn=<SubBackward0>)

In [90]:
az = -6*vz/tgo - 12*z/tgo**2 + 1.6
az

tensor(1.9743, grad_fn=<AddBackward0>)

In [92]:
torch.stack([ax, az])

tensor([-0.0818,  1.9743], grad_fn=<StackBackward>)

In [96]:
compute_actual(state)

tensor([0.0152, 1.6001], grad_fn=<StackBackward>)

In [98]:
optimizer.zero_grad()


input = torch.rand(5, requires_grad = True)

with torch.no_grad():
    actual = compute_actual(input)


In [99]:
actual

tensor([-0.3630,  2.0294])

In [104]:
net_prediction = net(input)
net_prediction

tensor([-0.0840,  0.0650], grad_fn=<AddBackward0>)

NameError: name 'net_prediction' is not defined

In [106]:
loss = criterion(net_prediction, actual)
loss

tensor(1.9683, grad_fn=<MseLossBackward>)

In [113]:
with torch.autograd.set_detect_anomaly(True):
    loss.backward()

../torch/csrc/autograd/python_anomaly_mode.cpp:40: UserWarning: No forward pass information available. Enable detect anomaly during forward pass for more information.


RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [ ]:
print('started training')
for epoch in range(2):  # loop over the dataset multiple times

    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        # get the inputs; data is a list of [inputs, labels]
        inputs, labels = data

        # zero the parameter gradients
        optimizer.zero_grad()

        # forward + backward + optimize
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        # print statistics
        running_loss += loss.item()
        if i % 2000 == 1999:    # print every 2000 mini-batches
            print('[%d, %5d] loss: %.3f' %
                  (epoch + 1, i + 1, running_loss / 2000))
            running_loss = 0.0

print('Finished Training')